version: "3.8"
    
services: 
  mosquitto:
    image: mqtt/rt
    ports:
      - "1883:1883"
      - "8883:8883"

  ingest:
    image: ingest/rt
    links:
      - mosquitto:mqtt/rt
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - '/home/iot/roomDBdata:/app/dbdata'

  web:
    image: webserver/rt
    ports: 
      - "8010:8010"
    links:
      - mosquitto:mqtt/rt
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - '/home/iot/roomDBdata:/app/dbdata'
      
#  findweb:
#    image: schollz/find3
#    ports: 
#      - "1884:1883"
#      - "8005:8003"
#    links:
#      - mosquitto:mqtt/rt
#    environment:
#      - "PYTHONUNBUFFERED=1"
#      - "MQTT_ADMIN=client"
#      - "MQTT_PASS=sekret"
#      - "MQTT_SERVER='192.168.1.161:1883'"
#      - "MQTT_EXTERNAL='0.0.0.0'"
#      - "MQTT_PORT=1883"
#    volumes:
#      - '/home/iot/FIND_DATA:/data'
